apiVersion: batch/v1
kind: Job
metadata:
  name: quick-qm-mpi-cpu
spec:
  template:
    spec:
      initContainers:
      - name: rclone
        image: rclone/rclone:latest
        command: ["rclone", "copy", "nrp-s3:quick-benchmarks", "/data"]
        volumeMounts:
        - name: quick-qm-benchmarks
          mountPath: "/data"
        - name: rclone
          mountPath: "/config/rclone/"
          readOnly: true
      containers:
      - name: quick
        image: kkricksdsu/quick:mpi-cpu
        command: ["/bin/bash", "-c", "cd /data/input && mpirun -np 2 water.in && sleep 3600"]
        # command: ["/bin/bash", "-c", "./runtest --serial --full && sleep 3600"]
        resources:
          limits:
            cpu: "2"
            memory: "4Gi"
          requests:
            cpu: "1"
            memory: "1Gi"
        volumeMounts:
        - name: quick-qm-benchmarks
          mountPath: "/data"
      restartPolicy: Never
      volumes:
      - name: rclone
        secret:
          secretName: rclone
      - name: quick-qm-benchmarks
        persistentVolumeClaim:
          claimName: quick-qm-benchmarks